server:
  port: 9090

mybatis:
  mapperLocations: classpath:mapping/*.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/forum?useUnicode=true&characterEncoding=UTF-8
    password: 1234
    username: root
    name: forum
    #使用Druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

bbs:
  encryption:
    seed: 0x3f2a3c7e
    salt: xzcawx

